Create DB tool
casper-network/casper-db-utils pull request #3
Opened 2022-03-01 15:01 UTC by nilz3ro

This PR introduces a rough draft version of the database utility tool.

2022-03-02 16:19 UTC, dwerner reviewed
Just a single comment/question from me.

2022-03-02 16:19 UTC, dwerner commented on src/lib.rs
> +    pub struct BlockHeader {
Would it be worth noting that the `BlockHeader` type could be referenced from the node? While it may be a heavyweight dependency, could it be worth extracting certain types there?

2022-03-03 15:34 UTC, sacherjj commented on src/main.rs
> +use lmdb_utils::{db, error::ToolError};
```suggestion
use casper_db_utils::{db, error::ToolError};
```

Required for build without errors for me.

2022-03-03 16:02 UTC, nilz3ro commented on src/lib.rs
> +    pub struct BlockHeader {
@Fraser999 asked me not to use `BlockHeader` from casper-node because it's too heavy.

2022-03-03 16:46 UTC, darthsiroftardis requested changes
Blocking the PR, as this code assumes a 1:1 mapping of headers to bodies.

2022-06-21 08:19 UTC, goral09 commented
@Fraser999 , can we close this PR?

2022-06-28 01:17 UTC, closed without merging